### ISSUE TITLE
fedoraproject downloads on AWS

### ISSUE THREAD

**Issue by raben2** [silpion/ansible-util#5]
Seems to be that https://download.fedoraproject.org/pub/epel redirect is not working or blocked when using AWS resources.

**Comment by spul** [comment]
No possibility for me to reproduce. I'd ask to review configuration options and if this issue is currently not addressable with role configuration provide more detailed information, logs, et cetera.

**Comment by spul** [comment]
Some time has passed, no further input... Closing this one.
